import { saveAs } from "file-saver";
import type { Question } from "./gemini";
import type { ReportRenderOptions } from "./types";

export async function generateQuestionsDocx(
  topic: string,
  questions: Question[],
  subject: string = "Subject",
  options: ReportRenderOptions = { includeAnswers: true, brandLabel: "Question Fetcher" }
) {
  const docx = await import("docx");
  const { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, BorderStyle, TableRow, TableCell, Table, WidthType } = docx;

  const children: any[] = [];

  // ── Title ──
  children.push(
    new Paragraph({
      children: [new TextRun({ text: "Question Bank", bold: true, size: 36, font: "Calibri" })],
      heading: HeadingLevel.HEADING_1,
      alignment: AlignmentType.CENTER,
      spacing: { after: 80 },
    }),
    new Paragraph({
      children: [new TextRun({ text: topic, size: 24, font: "Calibri", color: "555555", italics: true })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 80 },
    }),
    new Paragraph({
      children: [new TextRun({ text: `${questions.length} questions · Generated by ScanX`, size: 18, font: "Calibri", color: "999999" })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 300 },
    }),
    new Paragraph({
      children: [new TextRun({ text: `Prepared by ${options.brandLabel || "Question Fetcher"}`, size: 16, font: "Calibri", color: "888888", italics: true })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 220 },
    }),
    // Divider line
    new Paragraph({
      border: { bottom: { color: "CCCCCC", space: 1, size: 6, style: BorderStyle.SINGLE } },
      spacing: { after: 300 },
    })
  );

  // ── Questions ──
  questions.forEach((q, index) => {
    // Question header: number + type badge
    children.push(
      new Paragraph({
        children: [
          new TextRun({ text: `Q${index + 1}`, bold: true, size: 24, font: "Calibri" }),
          new TextRun({ text: `  [${q.type}]`, bold: true, size: 18, font: "Calibri", color: "2563EB" }),
          ...(q.year && q.year !== "N/A" ? [new TextRun({ text: `  (${q.year})`, size: 18, font: "Calibri", color: "888888" })] : []),
        ],
        spacing: { before: 300, after: 120 },
      })
    );

    // Question text
    children.push(
      new Paragraph({
        children: [new TextRun({ text: q.text, size: 22, font: "Calibri" })],
        spacing: { after: 160 },
      })
    );

    // Options — clean A/B/C/D layout
    q.options.forEach((opt, optIdx) => {
      const letter = String.fromCharCode(65 + optIdx);
      const isCorrect = q.answer.toUpperCase().startsWith(letter) || q.answer === opt;
      children.push(
        new Paragraph({
          children: [
            new TextRun({ text: `${letter}. `, bold: true, size: 21, font: "Calibri", color: isCorrect ? "16A34A" : "333333" }),
            new TextRun({ text: opt, size: 21, font: "Calibri", color: isCorrect ? "16A34A" : "333333" }),
          ],
          indent: { left: 400 },
          spacing: { after: 60 },
        })
      );
    });

    // Answer visibility toggle
    children.push(
      new Paragraph({
        children: options.includeAnswers
          ? [
              new TextRun({ text: "Answer: ", bold: true, size: 20, font: "Calibri", color: "16A34A" }),
              new TextRun({ text: q.answer, bold: true, size: 20, font: "Calibri", color: "16A34A" }),
            ]
          : [
              new TextRun({ text: "Answer: Hidden", italics: true, size: 18, font: "Calibri", color: "888888" }),
            ],
        spacing: { before: 120, after: 60 },
      })
    );

    // Source
    if (q.source && q.source !== "N/A") {
      children.push(
        new Paragraph({
          children: [new TextRun({ text: `Source: ${q.source}`, size: 16, font: "Calibri", color: "999999", italics: true })],
          spacing: { after: 60 },
        })
      );
    }

    // Topic tag
    children.push(
      new Paragraph({
        children: [new TextRun({ text: `Topic: ${q.topic}`, size: 16, font: "Calibri", color: "999999" })],
        spacing: { after: 200 },
      }),
      // Light divider between questions
      new Paragraph({
        border: { bottom: { color: "EEEEEE", space: 1, size: 4, style: BorderStyle.SINGLE } },
        spacing: { after: 100 },
      })
    );
  });

  const doc = new Document({
    sections: [{ properties: {}, children }],
  });

  const blob = await Packer.toBlob(doc);
  const suffix = options.includeAnswers ? "With_Answers" : "Question_Only";
  saveAs(blob, `${subject}_${String(topic || 'Report').replace(/\s+/g, "_")}_Question_Bank_${suffix}.docx`);
}
